-- ============================================================
-- SEED DATA STEPS
-- ============================================================
-- 
-- Since Supabase auth users must be created via the Auth API,
-- follow these steps to seed your database:
--
-- STEP 1: Create the Org Admin user
--   Go to Supabase Dashboard > Authentication > Users > Add User
--   Email: orgadmin@storeit.app   (username "orgadmin" maps to this email)
--   Password: OrgAdmin123!
--   
--   Then run this SQL (replace <ORG_ADMIN_UUID> with the user's UUID):
--
--   UPDATE public.profiles 
--   SET role = 'org_admin', full_name = 'Org Administrator', username = 'orgadmin'
--   WHERE id = '<ORG_ADMIN_UUID>';
--
-- STEP 2: Log in as Org Admin in the app and:
--   - Create a department (e.g., "Computer Science")
--   - Create a Super Admin for that department
--
-- STEP 3: Log in as Super Admin and:
--   - Create a class (e.g., "CS-2026 Batch A")
--   - Create a faculty account
--   - Assign faculty to the class
--   - Create student accounts
--   - Add students to the class
--
-- STEP 4: Log in as Faculty and:
--   - Select the assigned class
--   - Add form fields (Name, Roll No, Phone, Address, etc.)
--
-- STEP 5: Log in as Student and:
--   - View the form
--   - Fill in and submit details
--
-- ============================================================
-- QUICK SEED (after creating users via Auth):
-- ============================================================

-- Insert a sample department
-- INSERT INTO public.departments (id, name) 
-- VALUES ('d1000000-0000-0000-0000-000000000001', 'Computer Science');

-- Update org admin profile
-- UPDATE public.profiles 
-- SET role = 'org_admin', full_name = 'Org Admin', username = 'orgadmin', department_id = null
-- WHERE id = '<ORG_ADMIN_UUID>';

-- Update super admin profile  
-- UPDATE public.profiles
-- SET role = 'super_admin', full_name = 'Super Admin', username = 'superadmin',
--     department_id = 'd1000000-0000-0000-0000-000000000001'
-- WHERE id = '<SUPER_ADMIN_UUID>';
